apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod

resources:
  - config-map.yaml
  - ../../base

#patch json6902 demo replace patch
patches:
  - target:
      kind: Deployment
      name: nginx-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 10

  #demo patches json6902 add patch
  # patches:
  #Patch add logstash service mesh
  - target:
      kind: Deployment
      name: nginx-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/-
        value:
          name: logstash-mesh
          image: logstash:latest

# patch strategic-merge demo add
# patches:
#   - patch/api-depl.yaml
