apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

resources:
  - config-map.yaml
  - ../../base

#demo patches json6902 replace dev
patches:
  - target:
      kind: Deployment
      name: nginx-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 8

  - target:
      kind: Deployment
      name: nginx-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0
        value:
          name: newnametest
          image: httpd:alpine

  #----JSON6902 remove----#
  #demo patches json6902 delete creationTimestamp
  # patches:
  - target:
      kind: Deployment
      name: nginx-api
    patch: |-
      - op: remove
        path: /spec/template/metadata
        value:
          - creationTimestamp

#----Strategic Merge remove----#
#patch strategic-merge demo replace
# patches:
# - patch/api-depl.yaml
