apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-api
  name: nginx-api
spec:
  ports:
    - name: 80-30181
      port: 80
      protocol: TCP
      targetPort: 30181
  selector:
    app: nginx-api
  type: NodePort
status:
  loadBalancer: {}
