apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-depl.yaml
  - api-service.yaml

# Gán transformer namespace cho toàn bộ .yaml
namespace: thinhnp

# Đổi transformer image và tag trong deployment nếu trùng "name"
images:
  - name: httpd
    newName: nginx
    newTag: 1.21.0

#transformer Đặt tên đầu và cuối cho .yaml.
#VD: xxx thành LAB-xxx-dev
namePrefix: lab-
# nameSuffix: -dev

#Thêm Annotations
commonAnnotations:
  branch: master

#Thêm Labels vào toàn bộ yaml
labels:
  - includeSelectors: true
    pairs:
      app: bingo
      owner: thinhnp
      someName: someValue
